services:
  dash-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: opencv_dashboard
    ports:
      - "8050:8050"
    volumes:
      - ../:/app
    restart: always