services:
  cvdash-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: cvdash-container
    ports:
      - "8050:8050"
    volumes:
      - ../:/app
    restart: always